#!/bin/sh
#
# tracd startup
#
# $FreeBSD: branches/2017Q4/www/trac/files/tracd.in 340872 2014-01-24 00:14:07Z mat $

# PROVIDE: tracd
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable or configure tracd:
# tracd_enable (bool):		Set to "NO" by default.
#				Set it to "YES" to enable tracd.
# tracd_listen (str):		The host name or IP address to bind tracd to.
#				By default tracd listens 0.0.0.0, i.e. all the
#				available addresses on all interfaces.
# tracd_port (str):		The port number to bind to, 80 by default.
# tracd_pidfile (str):		When daemonizing, file to which to write pid
#				if not to /var/run/tracd.pid.
# tracd_envdir (str):		Directory of the project environments. Set to
#				"/home/trac" by default.
# tracd_env (str):		The project environment name while using single
# 				environment mode. The default is empty, meaning
#				multiproject mode.
# tracd_args (str):		Extra arguments passed to tracd startup
# 				command. Empty by default.
#

. /etc/rc.subr

name="tracd"
rcvar=tracd_enable

tracd_enable=${tracd_enable:-"NO"}
tracd_listen=${tracd_listen:-"127.0.0.1"}
tracd_port=${tracd_port:-"8080"}
tracd_pidfile=${tracd_pidfile:-"/var/run/tracd.pid"}
tracd_envdir=${tracd_envdir:-"/home/trac/shrimp"}
tracd_env=${tracd_env:-""}
tracd_args=${tracd_args:-""}

load_rc_config ${name}

command_args="--daemonize --hostname=${tracd_listen} --port=${tracd_port}"
command_args="${command_args} --pidfile=${tracd_pidfile} ${tracd_args}"

required_dirs="${tracd_envdir}/${tracd_env}"
pidfile=${tracd_pidfile}

_trac_env="${tracd_envdir}/${tracd_env}"
command_args="${command_args} --single-env"

command_args="/usr/local/bin/tracd ${command_args} ${_trac_env}"
command="/usr/local/bin/python2.7"

run_rc_command $1
